cargo-features = ["strip"]

[package]
name = "isar-core"
version = "0.1.0"
authors = ["Simon Leier <simonleier@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.7.3", features = [ "small_rng" ], default_features = false }
itertools = "0.9.0"
enum_dispatch = "0.3.4"
lmdb-sys = { path = "./lmdb-sys" }
libc = ""
wyhash = "0.4.1"
serde =  { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
serde_repr = "0.1.6"
thiserror = "1.0.22"
time = "0.2.22"
enum-ordinalize = "3.1.8"
hashbrown = "0.9"


[dev-dependencies]
cfg-if = "0.1.10"
tempfile = "3"
float_next_after = "0.1.5"

[lib]
crate-type=["cdylib", "rlib"]

[profile.release]
lto = true
codegen-units = 1
strip = "debuginfo"